---
title: "Лабораторная работа №2. Интерполирование кубическим сплайном дефекта"
---

Вариант 15

```{r}
N = 15
xi <- seq(-2, 2, len=6)
yi <- sin((N-5)/(N-10)*xi) + cos((N-5)/(N-10)*xi)
plot(xi, yi)
lines(spline(xi, yi, method="natural", n=100))

```


```{r}
n=5
xk <- xi
yk <- yi
a<-rep(0,n)
for (i in 1:6) {
  a[i]<-yk[i]
}

h<-rep(0,n)
for (i in 1:n) {
  h[i]<-xk[i+1] - xk[i]
}

c<-rep(0,n)
c[1]<-0
c[n+1]<-0
C<-seq(length = n)
C[1]<-0
C[2]<-1
for (i in 3:n) {
  C[i]<-(3*((yk[i] - yk[i-1])/h[i-1] - (yk[i-1] - yk[i-2])/h[i-2]) - h[i-2]*c[i-2] - 2*(h[i-2] + h[i-1])*c[i-1])/h[i-1]
}
c[2]<-3*((yk[n+1] - yk[n])/h[n] - (yk[n] - yk[n-1])/h[n-1])/(3*h[n-1] + 2*h[n])/(C[n-1] + C[n])
for (i in 3:n) {
  c[i]<-C[i]/c[2]
}
print(c)

b<-rep(0,n)
for (i in 1:(n-1)) {
  b[i]<-(yk[i+1] - yk[i])/h[i] - 1/3*h[i]*(c[i+1] + 2*c[i])
}
b[n]<-(yk[n+1] - yk[n])/h[n] - 2/3*h[n]*c[n]

d<-rep(0,n)
for (i in 1:(n-1)) {
  d[i]<-(c[i+1] - c[i])/3/h[i]
}
d[n]<--c[n]/3/h[n]
plot(xk, yk)
for (i in 1:n) {
  xi<-seq(xk[i], xk[i+1], length = 100)
  yi<-a[i] + b[i]*xi + c[i]*xi^2+ d[i]*xi^3
  lines(xi, yi, col="blue")
}
```

